#!/bin/sh

my_bat="BAT0"

case $BLOCK_BUTTON in
    1)  pgrep -x dunst >/dev/null && notify-send "<b>Battery:</b><br>$(upower -i /org/freedesktop/UPower/devices/battery_$my_bat| grep -E "state|time\ to\ full|percentage" | sed -E "s/ +/  /g" )" ;;
esac

capacity=$(cat /sys/class/power_supply/"$my_bat"/capacity) || exit
status=$(cat /sys/class/power_supply/"$my_bat"/status)

if [ "$capacity" -ge 75 ]; then
	color="#00ff00"
elif [ "$capacity" -ge 50 ]; then
	color="#ffffff"
elif [ "$capacity" -ge 25 ]; then
	color="#ffff00"
else
	color="#ff0000"
	warn="❗"
fi

[ -z $warn ] && warn=" "

[ "$status" = "Charging" ] && color="#ffffff"

printf "<span color='%s'>%s%s%s</span>" "$color" "$(echo "$status" | sed -e "s/,//;s/Discharging/🔋/;s/Not Charging/🛑/;s/Charging/🔌/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
