#!/bin/sh

date '+%Y %b %d (%a) %H:%M%p'

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "$(calcurse -D ~/.config/calcurse -d3)" ;;
	3) urxvt -e calcurse ;;
esac
