#!/bin/sh

# Status bar module for disk space
# $mount_point should be drive mountpoint
# $mount_icon is optional icon, otherwise mountpoint will displayed

mount_point="/home"
mount_icon="🏠"

[ -z "$mount_point" ] && exit

icon="$mount_icon"
[ -z "$mount_icon" ] && icon="$mount_point"

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send "<b>💽 Disk space:</b><br>$(df -h --output=target,used,size)" ;;
esac

printf "%s %s" "$icon" "$(df -h "$mount_point" | awk ' /[0-9]/ {print $3 "/" $2}')"
