#!/bin/bash

# The directory you want to use. You could use "$1" instead if you
# wanted to parametrize it.
DIR="$1"

# Internal Field Separator set to newline, so file names with
# spaces do not break our script.
IFS='
'
 
if [[ -d "${DIR}" ]]
then
  file_matrix=($(ls "${DIR}"))
  num_files=${#file_matrix[*]}
  xwallpaper --zoom "${DIR}/${file_matrix[$((RANDOM%num_files))]}"
fi

exit 0
